name: Build artifacts

on:
  push:
    branches: [ master ]
    tags:
    - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
        
    steps: 
    - name: Install Qt environment
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        install-deps: 'true'
        modules: 'all'
        cache: 'true'
        tools: 'tools_openssl_x64 tools_openssl_src'
        
    - name: Checkout codes
      uses: actions/checkout@v3
      
    - name: Build exectuable
      shell: cmd
      run: |
        for /f "delims=" %%d in ( 'vswhere.exe -latest -property installationPath' ) do @( call "%%d\VC\Auxiliary\Build\vcvars64.bat" )
        qmake "CONFIG+=qtquickcompiler" CONFIG+=release
        nmake

    - name: Set short SHA as package name
      if: "!startsWith(github.event.ref, 'refs/tags/')"
      run: echo "ARCHIVE_NAME=NyaTrace-$(git rev-parse --short HEAD)-MSVC-64bit" >> $env:GITHUB_ENV
      
    - name: Set tag version into env
      if: startsWith(github.event.ref, 'refs/tags/')
      run: echo "TAG_NAME=${env:GITHUB_REF_NAME}" >> $env:GITHUB_ENV
      
    - name: Set tag version as package name
      if: startsWith(github.event.ref, 'refs/tags/')
      run: echo "ARCHIVE_NAME=NyaTrace-${env:TAG_NAME}-MSVC-64bit" >> $env:GITHUB_ENV

    - name: Prepare workspace
      shell: pwsh
      run: |
        # Prepare workspace dir
        New-Item -ItemType Directory workspace
        # Prepare target dir
        New-Item -ItemType Directory workspace\${env:ARCHIVE_NAME}
        # Copy executable
        Copy-Item release\NyaTrace.exe workspace\${env:ARCHIVE_NAME}\
        
    - name: Win Deploy Qt
      shell: cmd
      run: |
        call "%Qt5_DIR%\bin\qtenv2.bat"
        chdir /d %GITHUB_WORKSPACE%\workspace\%ARCHIVE_NAME%
        windeployqt --qmldir %GITHUB_WORKSPACE% --release NyaTrace.exe

    - name: Prepare theme files
      shell: pwsh
      run: |
        Copy-Item -Recurse theme workspace\${env:ARCHIVE_NAME}\

    - name: Prepare MMDB notices
      shell: pwsh
      run: |
        New-Item -ItemType Directory workspace\${env:ARCHIVE_NAME}\mmdb
        $mmdbNotice = '请将 MMDB 文件放置在这里，具体操作请参见 https://github.com/Candinya/NyaTrace 相关的说明。'
        $mmdbNotice | Out-File workspace\${env:ARCHIVE_NAME}\mmdb\'请将 MMDB 文件放置在这里.txt'

    - name: Prepare OpenSSL DLLs
      shell: pwsh
      run: |
        Copy-Item ${env:Qt5_DIR}'\Tools\OpenSSL\Win_x64\bin\lib*-x64.dll' workspace\${env:ARCHIVE_NAME}\

    - name: Package artifacts
      shell: pwsh
      run: |
        Copy-Item LICENSE workspace\
        Compress-Archive -Path workspace\* ${env:ARCHIVE_NAME}'.zip'

    - name: Create release draft
      if: startsWith(github.event.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: NyaTrace - ${{ env.TAG_NAME }}
        tag_name: ${{ env.TAG_NAME }}
        generate_release_notes: true
        draft: true
        files: |
          ${{ env.ARCHIVE_NAME }}.zip
      env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
    
    - name: Upload built file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARCHIVE_NAME }}.zip
        path: workspace/
